name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DASK_SERVER_IP: 52.190.25.183
  BLOB_ACCOUNT_NAME: ${{ secrets.BLOB_ACCOUNT_NAME }}
  BLOB_ACCOUNT_KEY: ${{ secrets.BLOB_ACCOUNT_KEY }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -f kubernetes/Dockerfile -t navjotk/daks_test:latest .
    - name: Push to docker hub
      run: |
        docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        docker push navjotk/daks_test:latest
        
    - name: Test with pytest
      run: env > env_file && docker run --env-file env_file navjotk/daks_test:latest py.test -svx tests/
    
    - name: Run scripts
      run: |
        export PYTHONPATH=$PYTHONPATH:$PWD
        python generate_shot_data.py
        make overthrust_3D_initial_model_2D.h5
        python fwi.py
        python tests/test_gradient.py
